name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Projenin kullandığı .NET versiyonu

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build All Projects
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      # Eğer test projen varsa, buradaki yolu düzenle.
      # Örneğin: dotnet test "src/Tests/MyTests.csproj"
      run: dotnet test --configuration Release --no-build
      # Test projen yoksa bu adımı sil veya yorum satırı yap.

    - name: Publish API Gateway
      run: dotnet publish "ApiGateway/ApiGateway.csproj" --configuration Release --output ./publish_output/ApiGateway

    - name: Publish ProductApi
      run: dotnet publish "ProductApi/ProductApi.csproj" --configuration Release --output ./publish_output/ProductApi

    - name: Publish UserApi
      run: dotnet publish "UserApi/UserApi.csproj" --configuration Release --output ./publish_output/UserApi
    
    - name: Publish LoginApi
      run: dotnet publish "LoginApi/LoginApi.csproj" --configuration Release --output ./publish_output/LoginApi